name: Update Patreon Supporters

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: npm install axios

      - run: node script.js
        env:
          PATREON_TOKEN: ${{ secrets.PATREON_TOKEN }}
          CAMPAIGN_ID: ${{ secrets.CAMPAIGN_ID }}

      - name: Push supporters.json
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add supporters.json
          git commit -m "Update supporters" || echo "No changes"
          git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/WladekProd/SilentCherryAPI.git HEAD:main
